title: A Brief Description of Anthony Leapo
author: Anthony Leapo
email: tleapo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Learn a little bit more about me, Anthony Leapo, including my social media information, and 
 some of the activities I partake in. 
# social links
instagram_username: tonyleapo # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
