title: A Brief Description of Anthony Leapo
author: Anthony Leapo
email: tleapo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  In this site you can find out more about me, Anthony Leapo, including a picture of myself, my social media information, and
  some of the activities I partake in. 
# social links
instagram_username: tonyleapo # DO NOT include the @ character, or else the build will fail!
![FileSizeRender](https://user-images.githubusercontent.com/64381705/84446238-1252e500-ac13-11ea-91ec-8b1e98d6026a.png)

show_excerpts: true # set to false to remove excerpts on the homepage
theme : minima
